### ISSUE TITLE
user-agent

### ISSUE THREAD

**Issue by caioagiani** [rfoel/cnpj#1]
@rfoel, blz?
Fiz um projeto bem semelhante, no caso, um scheduler para rodar todos os dias e extrair todas as infos do CNPJ com base no CNAE;

O endpoint `api.casadosdados.com.br/v2/public/cnpj/search` retorna dados "básicos", então fiz um service para extrair os dados unitários: 

```js
@Injectable()
export class CnpjService {
  constructor(private _puppeteer: CommonService) {}

  async extract(param: string): Promise<Cnpj> {
    const request = await this._puppeteer.crawl(
      `https://casadosdados.com.br/solucao/cnpj/${param}`,
    );

    const response = await request.evaluate(
      () => window['__NUXT__'].data[0].cnpj,
    );

    await request.close();

    return response;
  }
}
```
---

https://github.com/rfoel/cnpj/blob/aeadde8bec6276c626e36073fc37d014c4f185d2/src/index.ts#L20

O ponto é: Não sei até que nível deseja escalar este projeto, mas, como o site `casadosdados.com.br` tem proteção `CloudFlare`, é questão de tempo (requests) até esse user-agent ser bloqueado.
Minha sugestão/solução é: Criar uma lista de user-agents e aplicar no puppeteer de forma randômica para cada requisição, segue utilitários:

https://gist.github.com/caioagiani/0a179cbf48ab7de8df99515744e772a5
https://gist.github.com/caioagiani/911b6fab52e6ab194d76da586ec42086

Ps: Fiz um list dos CNPJ na rota `solucao/cnpj/pesquisa-avancada` (semelhante ao seu), mas só guardo o CNPJ e pesquiso à parte no Service acima. Motivo: coletar os dados de contato como email/telefone e o restante das infos. 
Em pouco tempo de extração, meu request foi bloqueado com Captcha e Access denied, então fiz o random user-agent e funcionou aqui!

Resultado (simples):

```console
USER-AGENT: Mozilla/5.0 (X11; U; FreeBSD i386; ru-RU; rv:1.9.1.3) Gecko/20090913 Firefox/3.5.3
CNPJ 45162751000142 - KYRO BX LTDA - financeiro@pro-contaty.com.br

USER-AGENT: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.10) Gecko/20100915 Ubuntu/9.04 (jaunty) Firefox/3.6.10
CNPJ 45164310000180 - FUSION PLATAFORMA LTDA - bruna.paralegal@contecnica.com.br

USER-AGENT: Mozilla/5.0 (X11; U; Linux ppc; fr; rv:1.9.2.12) Gecko/20101027 Ubuntu/10.10 (maverick) Firefox/3.6.12
CNPJ 45163049000101 - WTNK SYSTEM LTDA - wtnksystem@outlook.com

USER-AGENT: Mozilla/5.0 (Windows; U; Windows NT 6.1; hu; rv:1.9.1.9) Gecko/20100315 Firefox/3.5.9 (.NET CLR 3.5.30729)
CNPJ 45161956000103 - PROMAIS SISTEMAS DE GESTAO LTDA - ocarmelin@ocarmelin.com.br

USER-AGENT: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; ja) Opera 11.00
CNPJ 45152663000160 - PAULO SILAS VIOLIN ARQUITETURA DE DADOS - victor@maximumcontroll.com.br

USER-AGENT: Opera/9.80 (X11; Linux i686; U; fr) Presto/2.7.62 Version/11.01
CNPJ 45162627000187 - YURI SANTOS LEMES PRODUCOES E PARTICIPACOES DIGITAIS - neto.luizmf@gmail.com
```

**Comment by rfoel** [comment]
Fala @caioagiani, não sei como você chegou nesse projeto mas agradeço os comentários.

Pra ser bem honesto eu não desejo escalar esse projeto, eu fiz só para uso pessoal mesmo, as vezes preciso de uma lista de CNPJs e queria um jeito fácil de pegar com todos os dados.

Eu imagino que ajudaria sim fazer essa randomização de user-agent, eu usaria algo pronto tipo [user-agents](https://www.npmjs.com/package/user-agents), ou  [random-useragent](https://www.npmjs.com/package/random-useragent) pra não precisar manter essa lista local.

**Comment by caioagiani** [comment]
@rfoel essas libs não funcionam (em longo prazo), tem bastante agents que o cloudflare barra.

**Comment by rfoel** [comment]
@caioagiani Entendi. Bom, se quiser abrir um PR e arrumar isso eu agradeço 😄

**Comment by fabioselau077** [comment]
@caioagiani eu fiz um parecido com o teu, mas demora muito para processar tudo.
Por exemplo, hoje teve 10k de novos cnpj e acessar cada e pegar os dados demora alguns segundos, com risco do Cloudflare pegar ainda.

Tentei achar algum endpoint do site que retorna mais informações, mas sem sucesso, será que tem algum outro site que retorna todos os dados de uma vez diretamente pela request? Vai economizar algumas dezenas de minutos de requests por dia.

**Comment by fabioselau077** [comment]
> @rfoel essas libs não funcionam (em longo prazo), tem bastante agents que o cloudflare barra. A ideia de criar um próprio é ter o controle de user-agentes trusted.

Caio, tem o plugin https://www.npmjs.com/package/puppeteer-extra-plugin-stealth para puppeteer que evita ser pego pelo Cloudflare, testei aqui com milhares de requests e passou todas (ou pelo menos 98% delas).

Como falei no comentário anterior, problema tá na quantidade de requests que tem que fazer pra ter mais dados, como email e telefone.

Vi q tem duas opções, fazendo request com proxy e depois utilizando o cheerio pra pegar o conteúdo pela tags no html ou utilizando o puppeteer com o plugin acima e pegando os dados pelo ```window['__NUXT__'].data[0].cnpj```.
Nessa segunda opção é mais lenta, mas tem os dados mais 'limpos'.

Tô me perguntando como a galera do casadosdados tem cnpj criados todos os dias se o dataset da Receita é atualizado 1x por mês.

Uma coisa que notei é que pelo casasadosdados só recupera 1000 cnpj, 50 páginas com 20 cnpj em cada... quando você envia a paginação para 51, ainda retorna a paginação da página 50, portanto só tem como recuperar 1k de cnpj por dia
